
services:
  postgre:
    image: postgres:latest
    container_name: postgredb
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test